#!/usr/bin/env python3
from __future__ import annotations

import argparse
import hashlib
import json
import os
import subprocess
import tempfile
from pathlib import Path
from typing import Any


ROOT = Path(__file__).resolve().parents[1]
CONTAINERS = ROOT / "containers"
SPEC_PATH = CONTAINERS / "helper-lock-spec.json"


def _sha256(path: Path) -> str:
    digest = hashlib.sha256()
    with path.open("rb") as handle:
        for block in iter(lambda: handle.read(1024 * 1024), b""):
            digest.update(block)
    return digest.hexdigest()


def _solve(
    micromamba: Path,
    root_prefix: Path,
    cache_root: Path,
    platform: str,
    glibc: str,
    name: str,
    environment: dict[str, Any],
) -> list[dict[str, Any]]:
    command = [
        str(micromamba),
        "create",
        "--dry-run",
        "--json",
        "--platform",
        platform,
        "--name",
        f"lock-{name}",
        "--override-channels",
        "--strict-channel-priority",
    ]
    for channel in environment["channels"]:
        command.extend(("--channel", str(channel)))
    command.extend(str(spec) for spec in environment["specs"])
    process_env = os.environ.copy()
    process_env.update(
        {
            "CONDA_OVERRIDE_GLIBC": glibc,
            "MAMBA_ROOT_PREFIX": str(root_prefix),
            "XDG_CACHE_HOME": str(cache_root),
        }
    )
    completed = subprocess.run(
        command,
        check=False,
        text=True,
        stdout=subprocess.PIPE,
        stderr=subprocess.PIPE,
        env=process_env,
    )
    if completed.returncode != 0:
        raise RuntimeError(
            f"micromamba solve failed for {name} ({completed.returncode}):\n"
            f"{completed.stderr}\n{completed.stdout}"
        )
    result = json.loads(completed.stdout)
    if result.get("success") is not True:
        raise RuntimeError(f"micromamba solve did not succeed for {name}: {result}")
    packages = list(result.get("actions", {}).get("LINK", []))
    if not packages:
        raise RuntimeError(f"micromamba returned no packages for {name}")
    for package in packages:
        if not package.get("url") or not package.get("sha256"):
            raise RuntimeError(f"package lacks URL/SHA-256 in {name}: {package}")
    return packages


def _write_explicit(path: Path, platform: str, packages: list[dict[str, Any]]) -> None:
    lines = [
        "# Generated by scripts/resolve-helper-locks.py; do not edit by hand.",
        f"# platform: {platform}",
        "@EXPLICIT",
    ]
    lines.extend(f"{package['url']}#{package['sha256']}" for package in packages)
    path.write_text("\n".join(lines) + "\n", encoding="utf-8")


def main() -> int:
    parser = argparse.ArgumentParser(
        description="Resolve reproducible linux-64 helper-container package locks"
    )
    parser.add_argument("--micromamba", required=True, type=Path)
    args = parser.parse_args()
    micromamba = args.micromamba.expanduser().resolve(strict=True)
    if not os.access(micromamba, os.X_OK):
        parser.error(f"micromamba is not executable: {micromamba}")

    spec = json.loads(SPEC_PATH.read_text(encoding="utf-8"))
    platform = str(spec["platform"])
    glibc = str(spec["virtual_packages"]["__glibc"])
    resolved: dict[str, Any] = {}
    with tempfile.TemporaryDirectory(prefix="igv-helper-lock-") as temporary:
        temp_root = Path(temporary)
        for name, environment in spec["environments"].items():
            packages = _solve(
                micromamba,
                temp_root / "mamba-root",
                temp_root / "cache",
                platform,
                glibc,
                name,
                environment,
            )
            lock_path = CONTAINERS / str(environment["lockfile"])
            _write_explicit(lock_path, platform, packages)
            resolved[name] = {
                "prefix": environment["prefix"],
                "lockfile": lock_path.name,
                "lockfile_sha256": _sha256(lock_path),
                "channels": environment["channels"],
                "requested_specs": environment["specs"],
                "packages": [
                    {
                        key: package.get(key)
                        for key in (
                            "name",
                            "version",
                            "build",
                            "subdir",
                            "url",
                            "sha256",
                            "size",
                        )
                    }
                    for package in packages
                ],
            }

    materials = {
        "schema_version": "igv-helper-materials-v1",
        "platform": platform,
        "virtual_packages": spec["virtual_packages"],
        "base_image": spec["base_image"],
        "micromamba": spec["micromamba"],
        "resolver": {
            "name": "micromamba",
            "version": subprocess.run(
                [str(micromamba), "--version"],
                check=True,
                text=True,
                stdout=subprocess.PIPE,
            ).stdout.strip(),
        },
        "environments": resolved,
    }
    (CONTAINERS / "materials.lock.json").write_text(
        json.dumps(materials, indent=2, sort_keys=True) + "\n", encoding="utf-8"
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
